name: dot
on:
 push:
  branches:
  - main
  - master
  
jobs:
 build:
  runs-on: ubuntu-latest
  
  steps:
  - name: first step
    run: |
      echo "jan"
      echo "feb"
      echo "march"

  - name: execute some shell cmds
    run: |
     pwd
     echo " $pwd"
     mkdir abc
     cd abc
     echo " created dir $pwd"
     touch brave
     chmod 777 brave
     echo " created the file $ls "
     pwd

  # - name: second step 
  # - name: third step
