name: dotnet
on:
 push:
  branches:
  - main
  - master
  
jobs:
 build:
  runs-on: ubuntu-latest
  
  steps:
  - name: first step
    run: |
      echo "jan"
      echo "feb"
      echo "march"

  - name: second step 
  - name: third step
