name: expert
on:
 push:
  # branches:
  # - main
  # - master
jobs:
 build:
  runs-on: ubuntu-latest
  
  steps:
   - name: first step
     run: |
      echo "one"
      echo "two" 

   - name: second steo
     run: | 
      echo "3"
      echo " 4" 
      echo 5 
      echo "  6 "
